# -*- coding: utf-8 -*-
"""PRODIGY_GA_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXb6IM1Aq4xiXG6rfWGPQf03TFZtGw6g
"""

pip install diffusers transformers torch accelerate

# ------------------------------------------
# Task-02: Image Generation using Pre-trained Model
# CPU ONLY VERSION (BEGINNER SAFE)
# ------------------------------------------

from diffusers import StableDiffusionPipeline
import torch

# Load pre-trained model (CPU)
model_name = "runwayml/stable-diffusion-v1-5"

pipeline = StableDiffusionPipeline.from_pretrained(
    model_name,
    torch_dtype=torch.float32
)

# FORCE CPU (IMPORTANT)
pipeline = pipeline.to("cpu")

# Text prompt
prompt = "A smart city with modern buildings and green energy"

# Generate image
image = pipeline(prompt).images[0]

# Save output
image.save("task02_output_image.png")

print("✅ Image generated successfully (CPU mode)")